src/components/Thread/Message.vue

Addresses the concerns in #53. 
This will offset the image loading, for each image, to between 750 and 1250 ms.
@Serubin want to test this and let me know if you see a difference, or if you would recommend a different approach?

Introduce offset for loading images, to avoid render lag

---

src/App.vue
src/components/Blacklists/Blacklists.vue
src/components/Conversations/ConversationItem.vue
src/components/Folders/Folders.vue
src/components/Passcode.vue
src/components/ScheduledMessages/ScheduledMessageItem.vue
src/components/ScheduledMessages/ScheduledMessages.vue
src/components/Sidebar.vue

Addresses changes suggested in #52 
@klinker24 Anything else we want to add before merging?

Material Design 2 Changes

---

package-lock.json
package.json
src/App.vue
src/components/Blacklists/BlacklistItem.vue
src/components/Blacklists/Blacklists.vue
src/components/Blacklists/CreateBlacklist.vue
src/components/Compose/Compose.vue
src/components/Compose/RecipientBar.vue
src/components/Conversations/Conversations.vue
src/components/Login.vue
src/components/Passcode.vue
src/components/Settings.vue
src/components/Sidebar.vue
src/components/Thread/Sendbar.vue
src/components/Thread/Settings.vue
src/main.js
src/utils/api_manager.js
src/utils/index.js
src/utils/translations.js

I have started working on internationalisation today, and the major part of the app is now translated in french.
New languages can easily be added and English is used as fallback.

Internationalization

---

src/components/Experiments.vue
src/router/index.js
src/store/plugins.js
src/store/state.js
src/utils/translations.js

See comments in #58 for inspiration and full details.
These will be used for A/B tests, to develop new features, and to allow people to implement tweaks, as they want. This page isn't going to be advertised anywhere and I do not want people to assume that these types of things will continue to be supported.
I put in an example preference, just as an example of the persistence. The functionality behind this example preference has not been implemented yet.

Experiments support

---

src/components/Blacklists/CreateBlacklist.vue
src/components/Thread/Thread.vue
src/utils/api_manager.js
src/utils/translations.js

Will wait to merge this, until this feature has been rolled out to the Android app.

Add support for creating a blacklist by phrase

---

src/components/Compose/RecipientBar.vue

Do not merge until the Android changes have been deployed.
For https://github.com/klinker-apps/messenger-issues/issues/620

Enable showing the contact types

---

package-lock.json
package.json
src/components/Settings.vue
src/components/Thread/Settings.vue

Just adds a color picker into settings, instead of having the user manually manipulate the hex colors.
Closes https://github.com/klinker-apps/messenger-issues/issues/749 and closes #92

Settings Color Picker

---

src/components/Compose/ContactEntryBar.vue

It does a few weird things, that I want to track here.... I have some stats on how often people send messages to numbers not in their contact list, and it is rarely. If they do, it is almost always a either a single phone number, or a huge list of phone numbers (that they obviously copied from a spreadsheet or something). With those stats in mind, I have no problem pushing this feature with these oddities. It seems like I will need to edit the library, to fix these things. I have no problem doing so, but it isn't top priority for me.
1. Say you type a phone number and tokenize it by ending with `;`. If you then try to type someone's contact name and complete it through the auto complete, it will wipe out the phone number you typed. The `multi-select-list` appears to manage the list of …

Enter phone numbers not in the contact list

---

README.md

Include License and License Compliance information in readme.

Add license compliance information

---

package-lock.json
package.json
src/components/Thread/Sendbar.vue

Improve emoji search by checking the initial to ensure it's an alphanumeric character. 
This allows for normal emoticons/smilies to be made without emoji search interference. There are also no emojis that start with a non alphanumeric, so there is no reason to search.

Improve Emoji Search

---

package.json
src/main.js
src/utils/api/account.js
src/utils/api/auto_reply.js
src/utils/api/blacklist.js
src/utils/api/contacts.js
src/utils/api/conversations.js
src/utils/api/devices.js
src/utils/api/drafts.js
src/utils/api/folders.js
src/utils/api/messages.js
src/utils/api/scheduled_messages.js
src/utils/api/templates.js
src/utils/api_manager.js

Switch ajax library from vue-h-ajax to axios.
The motivation for this encompasses two things - 
1) Testability - testing with the Vue context is annoying and not necessary
2) Maintainability - vue-ajax has very little support
Click testing... for now.

Move from vue-ajax to axios

---

src/App.vue
src/components/Conversations/ConversationItem.vue
src/components/Folders/FolderItem.vue
src/components/Sidebar.vue
src/router/index.js
src/utils/api/stream.js

Reduce error logging by resolving uncaught navigation error

Catch navigation errors

---

src/App.vue

Really, just catches the error. 
Should fix: https://app.bugsnag.com/pulsesms/pulse-sms-web/errors/5e61bb5b6e2e50001733ba06?filters[event.since][0]=30d&filters[error.status][0]=open

Fix registration error with service worker

---

package.json
src/App.vue
src/components/Settings.vue
src/utils/api/stream.js
src/utils/util.js

This should abstract notifications a little bit and hopefully reduce the errors we're seeing with new apis. If it doesn't, we can update the library!
Also fixes notification icon and abstracts the permission request process into `Util`

[#117] Add polyfill for notifications

---

src/components/Conversations/Conversations.vue

Fix #search-bar is null error on /archived
https://app.bugsnag.com/pulsesms/pulse-sms-web/errors/5e61cc2a1f6165001781a820

Fix #search-bar is null error on /archived

---

src/components/Thread/Thread.vue

There are several issues that rooting from this line: https://github.com/klinker-apps/pulse-sms-web/blob/a124a30731114e03b9a1e810efb89a8b9c1cb2bc/src/components/Thread/Thread.vue#L70
This occurs when either the thread route is wrong, or when the conversation cache is invalid or out of date, this will error. 
In one tab run the following in console (repalce thread id where necessary)
```
const conv = JSON.parse(localStorage.conversations)
conv[19168418653121] // Verify exists
delete conv[19168418653121] // Delete from cache
localStorage.setItem("conversations", JSON.stringify(conv))
```
In another tab load `/thread/19168418653121` with console open - this should error
https://app.bugsnag.com/pulsesms/pulse-sms-web/errors/5e61bd2f50a8a80018c57182?filters[error.status][0]=open …

Fix bad thread id issues

---

src/components/Thread/Thread.vue
src/utils/api/stream.js
src/utils/cache_manager.js

Fix exception in cache on message deletion

---

src/utils/api/stream.js

Should resolve https://github.com/klinker-apps/pulse-sms-issues/issues/939
Wasn't able to reproduce consistently - but this should resolve the issue.

Fix Notifications when logged out

---

src/App.vue
src/components/Experiments.vue
src/components/ImageViewer.vue
src/components/Login.vue
src/components/Passcode.vue
src/components/Settings.vue
src/components/Sidebar.vue
src/components/Snackbar.vue
src/utils/api_manager.js

Linting for major components of pulse. This is the first of what will be several PRs over time.
Click test around the app specifically:
* Sidebar
* Menus
* Settings
* Login page
* Image view
* Experiments page

[Linting] [Part 1] Core

---

src/components/Conversations/ConversationItem.vue
src/components/Conversations/Conversations.vue

Linting for major components of pulse. This is the first of what will be several PRs over time.
Click test around the app specifically:
* Conversation List
* Sidebar conversation list

[Linting] [Part 2] Conversations
